import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Descomplicando a contabilidade para profissionais <a href="https://nextjs.org">PJ</a>
        </h1>

        <p className={styles.description}>
          Removemos a complexidade e burocracia para ajudar você que deseja atuar no modelo de contratação PJ.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Grinply Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
